/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://maven.scijava.org/content/groups/public")
    maven("https://maven.scijava.org/content/groups/snapshots")
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    implementation("org.scijava:scijava-common:2.77.0")
    implementation(project(":mesh"))
    implementation("net.imglib2:imglib2:5.6.3")
    implementation("com.google.guava:guava:21.0")
    implementation("net.sf.trove4j:trove4j:3.0.3")
    implementation("org.smurn:jply:0.2.0")
    testImplementation("junit:junit:4.12")
}

group = "net.imagej"
version = "0.1.3-SNAPSHOT"
description = "ImageJ Mesh I/O plugins"
//sourceCompatibility = "1.8"

//configurations.all {
//}
//
//java {
//    withSourcesJar()
//}
//
//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}
//
//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}
