/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation("org.scijava:scijava-common:2.77.0")
    implementation(project(":mesh"))
    implementation("net.imglib2:imglib2:5.6.3")
    implementation("com.google.guava:guava:21.0")
    implementation("net.sf.trove4j:trove4j:3.0.3")
    implementation("org.smurn:jply:0.2.0")
    testImplementation("junit:junit:4.12")
}

version = "0.1.3-SNAPSHOT"
description = "ImageJ Mesh I/O plugins"