/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

group = "net.imagej"
version = "2.2.1-SNAPSHOT"
description = "ImageJ"
//sourceCompatibility = "1.8"

repositories {
    mavenLocal()
    maven("https://maven.scijava.org/content/groups/public")
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    listOf(":common", ":launcher", ":notebook", ":ops", ":updater").forEach {
        implementation(project(it))
    }
    implementation("io.scif:scifio:0.41.1")
    implementation("org.scijava:scijava-common:2.85.0")
    listOf(":mesh-io", ":plugins-batch", ":plugins-commands", ":plugins-tools", ":plugins-uploader-ssh",
        ":plugins-uploader-webdav", ":scripting", ":ui-swing").forEach {
        runtimeOnly(project(it))
    }
    runtimeOnly("org.scijava:scijava-io-http:0.2.1")
    runtimeOnly("org.scijava:scijava-plugins-commands:0.2.3")
    runtimeOnly("org.scijava:scijava-plugins-io-table:0.4.0")
    runtimeOnly("org.scijava:scijava-plugins-platforms:0.3.1")
    runtimeOnly("org.scijava:scijava-plugins-text-markdown:0.1.3")
    runtimeOnly("org.scijava:scijava-plugins-text-plain:0.1.3")
    runtimeOnly("org.scijava:script-editor:0.5.6")
    testImplementation("junit:junit:4.13")
}


//configurations.all { }

java.withSourcesJar()

publishing.publications.register("mavenJava", MavenPublication::class) {
    from(components["java"])
}

//tasks.withType(JavaCompile) {
//    options.encoding = 'UTF-8'
//}
