/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "imagej"

include(
    "common",
    "launcher",
    "mesh",
    "mesh-io",
    "notebook",
    "ops",
    "plugins-batch",
    "plugins-commands",
    "plugins-tools",
    "plugins-uploader-ssh",
    "plugins-uploader-webdav",
    "scripting",
    "ui-awt",
    "ui-swing",
    "updater"
)
