/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation(project(":common"))
    implementation("org.scijava:scijava-common:2.77.0")
    implementation("commons-lang:commons-lang:2.6")
    testImplementation("junit:junit:4.12")
    testImplementation("org.scijava:scijava-common:2.77.0")
}

version = "0.10.6-SNAPSHOT"
description = "ImageJ Updater"