/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    testImplementation(project(":common"))
}

version = "6.0.3-SNAPSHOT"
description = "ImageJ Launcher"