/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    testImplementation(project(":common"))
}

group = "net.imagej"
version = "6.0.3-SNAPSHOT"
description = "ImageJ Launcher"
//sourceCompatibility = '1.8'

//configurations.all {}

java.withSourcesJar()

publishing.publications.register("mavenJava", MavenPublication::class) {
    from(components["java"])
}

//tasks.withType(JavaCompile) {
//    options.encoding = 'UTF-8'
//}
