/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://maven.scijava.org/content/groups/public")
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    implementation(project(":common"))
//    implementation("net.imagej:imagej-deprecated:0.1.2")
    implementation("net.imglib2:imglib2:5.6.3")
    implementation("net.imglib2:imglib2-algorithm:0.11.1")
    implementation("org.scijava:scijava-common:2.77.0")
    implementation("org.scijava:scijava-table:0.4.0")
    implementation("com.github.sbridges.object-inspector:object-inspector:0.1")
    implementation("net.iharder:base64:2.3.8")
}

group = "net.imagej"
version = "0.8.2-SNAPSHOT"
description = "ImageJ Plugins: Commands"
//sourceCompatibility = "1.8"
//
//configurations.all {
//}
//
//java {
//    withSourcesJar()
//}
//
//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}
//
//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}
