/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation(project(":common"))
    implementation(project(":deprecated"))
    implementation(project(":updater"))
    implementation("net.imglib2:imglib2:5.8.0")
    implementation("net.imglib2:imglib2-roi:0.8.1")
    implementation("org.scijava:scijava-common:2.82.0")
    implementation("org.scijava:scijava-ui-awt:0.1.7")
    implementation("org.scijava:scijava-ui-swing:0.13.1")
    implementation("com.miglayout:miglayout-swing:5.2")
    implementation("org.jfree:jfreechart:1.5.0")
    implementation("org.jhotdraw:jhotdraw:7.6.0")
    runtimeOnly(project(":ui-awt"))
    testImplementation("junit:junit:4.12")
}

version = "0.23.3-SNAPSHOT"
description = "ImageJ UI: Swing"