/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation(project(":common"))
    implementation("net.imglib2:imglib2:5.10.0")
    implementation("net.imglib2:imglib2-roi:0.10.3")
    implementation("org.scijava:scijava-common:2.83.3")
    implementation("edu.ucar:udunits:4.3.18")
    testImplementation("junit:junit:4.13")
}

version = "0.1.6-SNAPSHOT"
description = "ImageJ Deprecated"