/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://maven.scijava.org/content/groups/public")
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    implementation(project(":updater"))
    implementation("org.scijava:scijava-common:2.77.0")
    implementation("com.jcraft:jsch:0.1.55")
    testImplementation("junit:junit:4.12")
    testImplementation(project(":updater"))
    testImplementation("org.scijava:scijava-common:2.77.0")
}

group = "net.imagej"
version = "0.3.3-SNAPSHOT"
description = "ImageJ Plugins: Uploader: SSH"
//sourceCompatibility = "1.8"
//
//configurations.all {
//}
//
//java {
//    withSourcesJar()
//}
//
//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}
//
//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}
