/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    // [Gradle]
    implementation(project(":common"))
    implementation(project(":updater"))
    implementation("org.scijava:scijava-common:2.77.0")
    implementation("com.jcraft:jsch:0.1.55")
    testImplementation("junit:junit:4.12")
    testImplementation(project(":updater"))
    testImplementation("org.scijava:scijava-common:2.77.0")
}

version = "0.3.3-SNAPSHOT"
description = "ImageJ Plugins: Uploader: SSH"