/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation("io.scif:scifio:0.41.0")
    implementation("net.imagej:ij1-patcher:1.1.0")
    implementation("net.imagej:ij:1.53c")
    implementation(project(":common"))
    implementation(project(":deprecated"))
    implementation("net.imglib2:imglib2:5.10.0")
    implementation("net.imglib2:imglib2-ij:2.0.0-beta-46")
    implementation("net.imglib2:imglib2-realtransform:3.0.0")
    implementation("net.imglib2:imglib2-roi:0.10.3")
    implementation("org.scijava:scijava-common:2.83.3")
    implementation("org.scijava:scijava-search:0.7.0")
    implementation("org.scijava:scijava-table:0.6.1")
    implementation("org.scijava:scijava-ui-awt:0.1.7")
    implementation("org.scijava:scijava-ui-swing:0.13.2")
    implementation("org.scijava:script-editor:0.5.6")
    implementation("com.fifesoft:autocomplete:3.1.0")
    implementation("com.fifesoft:languagesupport:3.1.0")
    implementation("com.fifesoft:rsyntaxtextarea:3.1.1")
    implementation("org.javassist:javassist:3.27.0-GA")
    implementation("com.miglayout:miglayout-swing:5.2")
    implementation("net.sf.trove4j:trove4j:3.0.3")
    testImplementation("junit:junit:4.13")
    testImplementation("org.openjdk.jmh:jmh-core:1.23")
    testImplementation("org.openjdk.jmh:jmh-generator-annprocess:1.23")
    testImplementation("org.scijava:scripting-groovy:0.3.0")
}

version = "0.37.5-SNAPSHOT"
description = "ImageJ Legacy Bridge"