/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation("org.scijava:batch-processor:0.3.0")
    implementation("org.scijava:scijava-table:0.4.0")
    implementation(project(":common"))
    implementation("io.scif:scifio:0.37.3")
    testImplementation("junit:junit:4.12")
    testImplementation("org.scijava:scripting-groovy:0.2.7")
}

version = "0.1.2-SNAPSHOT"
description = "ImageJ Plugins Batch"