/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://maven.scijava.org/content/groups/public")
    maven("https://repo.maven.apache.org/maven2")
}

dependencies {
    implementation("org.scijava:batch-processor:0.3.0")
    implementation("org.scijava:scijava-table:0.4.0")
    implementation(project(":common"))
    implementation("io.scif:scifio:0.37.3")
    testImplementation("junit:junit:4.12")
    testImplementation("org.scijava:scripting-groovy:0.2.7")
}

group = "net.imagej"
version = "0.1.2-SNAPSHOT"
description = "ImageJ Plugins Batch"
//sourceCompatibility = "1.8"
//
//configurations.all {
//}
//
//java {
//    withSourcesJar()
//}
//
//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}
//
//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}
