/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation(project(":common"))
    implementation(project(":mesh"))
    implementation("net.imglib2:imglib2:5.9.0")
    implementation("net.imglib2:imglib2-algorithm:0.11.2")
    implementation("net.imglib2:imglib2-algorithm-fft:0.2.0")
    implementation("net.imglib2:imglib2-realtransform:3.0.0")
    implementation("net.imglib2:imglib2-roi:0.10.3")
    implementation("org.scijava:parsington:2.0.0")
    implementation("org.scijava:scijava-common:2.83.1")
    implementation("org.scijava:scijava-search:0.7.0")
    implementation("org.scijava:scripting-javascript:0.5.0")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.joml:joml:1.9.25")
    implementation("org.ojalgo:ojalgo:45.1.1")
    implementation("gov.nist.math:jama:1.0.3")
    testImplementation("junit:junit:4.13")
    testImplementation("org.scijava:junit-benchmarks:0.7.4-scijava")
    testImplementation("io.scif:scifio:0.41.0")
    // TODO Could not find jffi-1.2.20-native.jar (com.github.jnr:jffi:1.2.20).
//    testImplementation("org.scijava:scripting-jython:1.0.0")
    testImplementation("net.imagej:ij:1.53c")
    testImplementation("net.imglib2:imglib2-ij:2.0.0-beta-46")

    // [Gradle] added
    implementation("org.scijava:scijava-table:0.6.1")
}

version = "0.45.8-SNAPSHOT"
description = "ImageJ Ops"