/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    // [Gradle]
    implementation(project(":common"))
    implementation(project(":updater"))
    implementation("org.scijava:scijava-common:2.77.0")
    implementation("org.apache.jackrabbit:jackrabbit-webdav:2.19.1")
    implementation("org.apache.httpcomponents:httpclient:4.5.6")
    implementation("org.apache.httpcomponents:httpcore:4.4.11")
    testImplementation("junit:junit:4.12")
    testImplementation(project(":updater"))
}

version = "0.3.3-SNAPSHOT"
description = "ImageJ Plugins: Uploader: WebDAV"